- name: Generate shares.conf file
  config_template:
    src: netapp/shares.conf.j2
    dest: /tmp/shares.conf
    config_type: ini

- name: Read configs into memory
  slurp:
    src: "/tmp/shares.conf"
  register: "shares_conf"

- name: Create cinder-volume-netapp configmaps
  ignore_errors: yes
  k8s_v1_config_map:
    name: cinder-volume-netapp
    namespace: "{{ namespace }}"
    state: present
    debug: yes
    labels:
      service: cinder-volume-netapp
    data:
      config.json: |
        {
            "command": "/usr/bin/cinder-volume --config-file /usr/share/cinder/cinder-dist.conf --config-file /etc/cinder/cinder.conf",
            "config_files": [
                {
                    "source": "/var/lib/kolla/config_files/cinder.conf",
                    "dest": "/etc/cinder/cinder.conf",
                    "owner": "cinder",
                    "perm": "0600"
                },
                {
                    "source": "/var/lib/kolla/config_files/shares.conf",
                    "dest": "/etc/cinder/shares.conf",
                    "owner": "cinder",
                    "perm": "0600"
                }
            ],
            "permissions": [
                {
                    "path": "/var/lib/cinder",
                    "owner": "cinder:cinder",
                    "recurse": true
                },
                {
                    "path": "/var/log/kolla/cinder",
                    "owner": "cinder:cinder",
                    "recurse": true
                }
            ]
        }

      cinder.conf: |
        {{cinder_conf['content'] | b64decode}}

      shares.conf: |
        {{shares_conf['content'] | b64decode}}

- name: Create Cinder Volume Deployment
  openshift_v1_deployment_config:
    name: cinder-volume-netapp
    namespace: "{{ namespace }}"
    service_account_name: "{{ service_account }}"
    labels:
      app: cinder-volume-netapp
      service: cinder-volume-netapp
    replicas: 1
    spec_template_metadata_labels:
      app: cinder-volume-netapp
      service: cinder-volume-netapp
    containers:
    - name: cinder-volume
      image: tripleoupstream/centos-binary-cinder-volume:latest
      volumeMounts:
        - name: kolla-config
          mountPath: /var/lib/kolla/config_files/
      env:
        - name: TZ
          value: UTC
        - name: KOLLA_CONFIG_STRATEGY
          value: COPY_ALWAYS
        - name: KOLLA_KUBERNETES
          value: ""
    volumes:
      - name: kolla-config
        config_map:
          name: cinder-volume-netapp

